# Generated by Django 4.2.4 on 2024-08-09 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='canceled_instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='session',
            name='confirmed_instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='session',
            name='pending_instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
