# Generated by Django 4.2.4 on 2024-06-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0002_alter_admindata_learning_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='location',
            new_name='learning_organization_location',
        ),
    ]
