# Generated by Django 4.2.4 on 2024-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0003_rename_location_room_learning_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplicationinstance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
