# Generated by Django 4.2.4 on 2024-07-01 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0004_instructorapplicationinstance_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('sessions', models.ManyToManyField(related_name='approval_tokens', to='heu.session')),
            ],
        ),
    ]
