# Generated by Django 4.2.4 on 2024-08-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0005_alter_session_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardCodedQuestionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heu.question')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nickname for Module')),
                ('questions', models.ManyToManyField(related_name='question_counter', to='heu.hardcodedquestioncounter')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heu.module')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nickname for Phase')),
                ('modules', models.ManyToManyField(related_name='module_counter', to='heu.modulecounter')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heu.phase')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nickname for Lesson Plan')),
                ('phases', models.ManyToManyField(related_name='phase_counter', to='heu.phasecounter')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heu.lessonplan'),
        ),
    ]
