# Generated by Django 4.2.4 on 2024-07-16 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0005_sessionapprovaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
