# Generated by Django 4.2.4 on 2024-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0007_alter_session_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardCodedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('audio', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('json', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='instructors',
        ),
        migrations.CreateModel(
            name='HardCodedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(related_name='question', to='heu.hardcodedquestion')),
            ],
        ),
    ]
