# Generated by Django 4.2.4 on 2024-08-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0009_hardcodedquestioncounter_delete_questioncounter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='suggested_duration',
            new_name='suggested_duration_seconds',
        ),
    ]
