# Generated by Django 4.2.4 on 2024-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0010_rename_suggested_duration_module_suggested_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='description',
            field=models.TextField(default='Default Lesson Plan'),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Default Module'),
        ),
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(default='Default Learning Phase'),
        ),
        migrations.AddField(
            model_name='phase',
            name='type',
            field=models.CharField(default='Learning Phase'),
        ),
    ]
