# Generated by Django 4.2.4 on 2024-07-26 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heu', '0011_hardcodedstudentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardcodedstudentprogress',
            name='intermediate_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='hardcodedstudentprogress',
            name='intermediate_timing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
