# Generated by Django 4.2.4 on 2024-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
