# Generated by Django 4.2.4 on 2024-06-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='learning_center',
            new_name='learning_organization',
        ),
    ]
