# Generated by Django 4.2.4 on 2024-06-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0002_alter_question_audio_alter_question_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LookupTable',
            new_name='LookupIndex',
        ),
    ]
