# Generated by Django 4.2.4 on 2024-06-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0003_alter_session_enrolled_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_form_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('admin_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logion.admindata')),
                ('learning_organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logion.learningorganizationlocation')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logion.admindata')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logion.instructordata')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logion.instructorapplicationtemplate')),
            ],
        ),
    ]
