# Generated by Django 4.2.4 on 2023-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0003_remove_comment_user_id_remove_response_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='probability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
