# Generated by Django 4.2.4 on 2024-06-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0004_instructorapplicationtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='learning_organization',
        ),
        migrations.AddField(
            model_name='instructorapplicationinstance',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='learning_organization_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logion.learningorganizationlocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructorapplicationinstance',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logion.admindata'),
        ),
        migrations.CreateModel(
            name='SessionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_weeks_for_density_sliding_window', models.IntegerField()),
                ('num_weeks_for_total_sessions_sliding_window', models.IntegerField()),
                ('average_sessions_per_week_in_density_window', models.IntegerField()),
                ('num_of_weeks_with_at_least_one_session_in_total_window', models.IntegerField()),
                ('session_length_hours', models.IntegerField(default=1)),
                ('learning_organization_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logion.learningorganizationlocation')),
            ],
        ),
    ]
