# Generated by Django 4.2.4 on 2024-06-13 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0004_scorehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('num_attempts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreHistory',
        ),
    ]
