# Generated by Django 4.2.4 on 2024-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0005_remove_session_learning_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionrequirements',
            old_name='session_length_hours',
            new_name='minimum_session_hours',
        ),
        migrations.RemoveField(
            model_name='sessionrequirements',
            name='average_sessions_per_week_in_density_window',
        ),
        migrations.RemoveField(
            model_name='sessionrequirements',
            name='learning_organization_location',
        ),
        migrations.RemoveField(
            model_name='sessionrequirements',
            name='num_of_weeks_with_at_least_one_session_in_total_window',
        ),
        migrations.RemoveField(
            model_name='sessionrequirements',
            name='num_weeks_for_density_sliding_window',
        ),
        migrations.RemoveField(
            model_name='sessionrequirements',
            name='num_weeks_for_total_sessions_sliding_window',
        ),
        migrations.AddField(
            model_name='sessionrequirements',
            name='minimum_avg_days_per_week',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='sessionrequirements',
            name='minmum_num_weeks_consecutive',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sessionrequirements',
            name='num_exempt_weeks',
            field=models.IntegerField(default=2),
        ),
    ]
