# Generated by Django 4.2.4 on 2024-06-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0005_assessment_delete_scorehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
