# Generated by Django 4.2.4 on 2024-06-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0006_alter_assessment_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(default=dict),
        ),
    ]
