# Generated by Django 4.2.4 on 2024-06-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0007_alter_assessment_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
