# Generated by Django 4.2.4 on 2024-06-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0008_admindata_instructordata_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ad', 'admin'), ('in', 'instructor'), ('st', 'student'), ('hs', 'heu-staff')], default='st', max_length=255),
            preserve_default=False,
        ),
    ]
