# Generated by Django 4.2.4 on 2024-06-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logion', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeuStaffData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='admindata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructordata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
