import Head from "next/head";
import Header from "../../components/header"
import styles from "../styles/Home.module.css"

export default function CustomErrorPage() {
  return (
    <>
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <div style={{"margin": "10px"}}>
            Error. This application is only for approved users. To request
            access, please reach out to: x.
        </div>
      </main>
    </>
  );
}
