import Head from "next/head";
import Header from "../../components/header"
import styles from "../styles/Start.module.css"
import Image from "next/image";
import background from "../../public/background.png"
import { demo } from "./api/services/use-all-author-texts";


export default function Start() {
  const { res } = demo({
    url: `/api/data/demo`,
    method: "POST",
    headers: {
      "content-type": "application/json",
    }
  });
  return (
    <>
      <Head>
        <title>Start</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        {/* <Header></Header> */}
        {/* <div className={styles.background}> */}
          <div className={styles.container}>
            {/* <h1>Welcome to Logion</h1> */}
            {/* <h2>{"The aim of this project is to develop an NLP tool that aids the restoration and elucidation of premodern Greek texts. The name of our tool is Logion, which means  ‘oracle’ in ancient Greek: we chose it to emphasize that machine-generated results require human interpretation. Logion does not offer solutions to philological problems; it can, however, provide concrete suggestions and general inspiration. For our Proof of Concept, we focused on the Byzantine author Michael Psellos. We are now also working on Aristotle, Galen and other major Greek authors.  In future, we intend to adapt our model to serve other languages. Our aspiration is to use Natural Language Processing to help preserve and elucidate the global archive of pre-modern texts."}</h2> */}
            <button className={styles.button}>Start</button>
          </div>
        {/* </div> */}
        {/* <Auth0Features /> */}
      </main>
    </>
  );
}


